export const COOKS = [
    {cookName: "Christian Pullisic",
    cookNum:1,
    cuisine: "Mexican",
    rating:3,
    cookImg: "/assets/images/chef1.jpg",
    alt:"cook 1 img",
    page:"cook1.html",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." ,
    featured:true,
    foodImg1: "/assets/images/food11.jpg",
    foodImg2: "/assets/images/food12.jpg",
    },
    {cookName: "N'golo Kante",
    cookNum:2,
    cuisine:   "Ethopian",
    rating:4.8,
    cookImg: "/assets/images/chef2.jpg",
    alt:"cook 2 img",
    foodImg1: "/assets/images/food21.jpg",
    foodImg2: "/assets/images/food22.jpg",
    page:"cook2.html",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." ,    
    featured:false

    },
    {cookName: "Ji So-yun",
    cookNum:3,
    cuisine: "Pakistani",
    rating:5,
    cookImg: "/assets/images/chef3.jpg",
    alt:"cook 3 img",
    foodImg1: "/assets/images/food31.jpg",
    foodImg2: "/assets/images/food32.jpg",
    page:"cook3.html",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    featured:true
    },
    {cookName: "Magdalena Eriksson",
    cookNum:4,
    cuisine: "Italian",
    rating:4.2,
    cookImg: "/assets/images/chef4.jpg",
    alt:"cook 4 img",
    foodImg1: "/assets/images/food41.jpg",
    foodImg2: "/assets/images/food42.jpg",
    page:"cook4.html",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", 
    featured:true
    }
]
